# Token 配置
token:
  # token名称
  name: x-token
  prefix:

# Sa-Token 配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: ${token.name}
  # token 前缀, 前端提交 token 时应该填写的固定前缀，格式样例(satoken: Bearer xxxx-xxxx-xxxx-xxxx)
  token-prefix: ${token.prefix}
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: ${token.timeout}
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # jwt秘钥
  jwt-secret-key: ${token.secret}

# 下面是环境区分，多个配置以 ‘---’ 分开
---
# dev环境配置
spring:
  config:
    activate:
      on-profile: dev
token:
  # 密钥
  secret: 52ae521312f6461083435e045900486e
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: -1
template:
  enable:
    access-control: false

---
# test环境配置
spring:
  config:
    activate:
      on-profile: test
token:
  # 密钥
  secret: 52ae521312f6461083435e045900486e
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
template:
  enable:
    access-control: true

---
# pre环境配置
spring:
  config:
    activate:
      on-profile: pre
token:
  # 密钥
  secret: a77f70ddf0e64c34a2b96e3ee0c43779
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
template:
  enable:
    access-control: true

---
# prod环境配置
spring:
  config:
    activate:
      on-profile: prod,prod-zone1,prod-zone2
token:
  # 密钥
  secret: a77f70ddf0e64c34a2b96e3ee0c43779
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
template:
  enable:
    access-control: true
