spring:
  config:
    import: classpath:bootstrap.yml # 在Spring Boot 2.7.x版本中，默认情况下，bootstrap.yml件不再被自动加载
  profiles:
    include: gracefulresponse,developer,feign,resilience4j,sentinel,redis,rabbitmq,rocketmq,messagedriven,cachemanager,datasource,canal # 项目中增加配置application-*.yml可覆盖boot-starter-*的默认配置application-*.yml
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.qq.com
    port: 465
    username: 888888888@qq.com # 发件人
    password: 111111111 # 发件人密码
    properties:
      mail.smtp.ssl.enable: false # 使用ssl连接
      mail.smtp.ssl.trust: '*' # 信任所有主机
  cloud:
    loadbalancer:
      eager-load: # spring-cloud-commons-3.1.8 没有eager-load，参考spring cloud高版本实现饥饿加载
        clients: template-user

template:
  sequence:
    datacenterId: 1
  threadpool:
    corePoolSize: 10
    maxPoolSize: 20
    queueCapacity: 200
    keepAliveSeconds: 60
    threadNamePrefix: t-subTask-
    waitForTasksToCompleteOnShutdown: true
    awaitTerminationSeconds: 60
